### ISSUE TITLE
Carousel auto height = height of selected image

### ISSUE THREAD

**Issue by JaySunSyn** [FabricElements/skeleton-carousel#44]
The requirements:
1. The width of the carousel 100%
2. The height of the carousel (not only the visible image) should be the image height.

Same as you would have:

```css
img {
  width: 100%;
}
```
```html
<img src="img.png">
```

An approach could be:

1. add `--skeleton-carousel-container` mixin; With that we can set `position: relative` and the height of the carousel will be equal to the height of the **largest** loaded image.

```css
#itemsContainer {
    @apply --layout-fit;
    @apply --layout-inline;
    @apply --skeleton-carousel-container;
}
```

2. I guess the height of the non selected images are stretching the carousel. How to set the height of the carousel to the currently loaded image? Either set `height: 0` or `display: none`

```css
#itemsContainer ::slotted(.selected) {
        opacity: 1;
        height: 100%;
}
/** Problem: next image is only visible when fully swiped */
#itemsContainer ::slotted(:not(.selected)) {
        opacity: .8;
        height: 0;
}
/** Makes above problem a tiny little bit less */
:host[swiping] > #itemsContainer ::slotted(*) {
        height: 100% !important;
}
```

May you help out here? Do you have a better solution in mind?

**Comment by ernysans** [comment]
@JaySunSyn This carousel ins not only for images, and we need to consider the the vertical layout.

You can set `@apply --layout-flex-auto;` you an `iron-image` that's the best way.
https://github.com/FabricElements/skeleton-carousel/blob/master/demo/index.html#L35

If you really need to set an `img` tag, I will recommend to fix it with box sizing.
https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
You can apply this to your component directly, you don't need to set this with the `skeleton-carousel` mixings.

```css
img {
width: 100%;
box-sizing: content-box;
}
```

**Comment by JaySunSyn** [comment]
Thanks!

The actual problem that I have is that the carousel/slide is always as big as the biggest image which looks like below.

In other words, the carousel doesn't work well with images having different sizes (while wanting the images not to be cropped)

![image](https://user-images.githubusercontent.com/5872432/32384249-95565a14-c0ba-11e7-90b5-7f6eac1a0b5c.png)

Having:
```css
#itemsContainer {
        @apply --layout-fit;
        @apply --layout-inline;
        position: relative;
}
```

1. The gray area is so big because there is one big image in the slides.

2. The slide is not centered.

**Comment by ernysans** [comment]
@JaySunSyn You can't apply those mixings to `#itemsContainer` the carousel is going to broke.

You only need to apply the styles to the `iron-image` and add this property `sizing="contain"` just like on the `Option 1` of my previews comment.
The problem Is that you always need to specify  the `sizing` property, otherwise the iron image is not going to fit the content.

**Comment by JaySunSyn** [comment]
Not sure I communicated this right :)

I created a branch for this issue: https://github.com/JaySunSyn/skeleton-carousel/tree/issue-44-demo

Is it possible, that the **carousel** changes its height based on the current displayed image?

In the demo you see, that the height of the carousel stays constant to it's set min-height of 300px rather than changing its size. Which is of course often wanted, but I'd need the carousel height to be dynamically sized based on the image loaded.

**Comment by ernysans** [comment]
I understand now. No, it's not posible. That behavior wont be a available for this carousel because this will only work on the horizontal layout, the vertical layout wont work with this specifications.
The spaces, transformations and animations are using `%` for everything to make it responsive and also to keep the carousel consistent on `horizontal` and `vertical` layout.
You could force it with styles in your case but it wont be a default behavior on this component.

**Comment by ernysans** [comment]
I found the problem. Is just a css issue. I'll push the changes later today.

**Comment by ernysans** [comment]
@JaySunSyn I think we have it now.


This is the best way. [demo](https://github.com/FabricElements/skeleton-carousel/blob/master/demo/index.html#L35)

```css
iron-image {
  @apply --layout-flex-auto;
  margin: 0 auto;
}
skeleton-carousel {
  --skeleton-carousel-item: {
    height: 100px; /* or what you need */
  };
  --skeleton-carousel-item-selected: {
    height: auto; /* or what you need */
  };
}
```
```html
<skeleton-carousel dots nav>
  <div>
    <iron-image data-src="https://source.unsplash.com/category/nature/400x600"></iron-image>
    <h3>Title 1</h3>
  </div>
  <div>
    <iron-image data-src="https://source.unsplash.com/category/food/400x300"></iron-image>
    <h3>Title 2</h3>
  </div>
  <div>
    <iron-image data-src="https://source.unsplash.com/category/buildings/400x400"></iron-image>
    <h3>Title 3</h3>
  </div>
</skeleton-carousel>
```
